"""empty message

Revision ID: 15e5985bada9
Revises: 
Create Date: 2022-05-19 13:03:11.448484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15e5985bada9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('adminid', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('adminid'),
    sa.UniqueConstraint('email', name='unique_mail')
    )
    op.create_table('user_profiles',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('userid'),
    sa.UniqueConstraint('email', name='unique_email')
    )
    op.create_table('reports',
    sa.Column('reportid', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('division', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('crime', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['user_profiles.userid'], ),
    sa.PrimaryKeyConstraint('reportid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    op.drop_table('user_profiles')
    op.drop_table('admin')
    # ### end Alembic commands ###
